# Wrangler 配置文件
name = "recipe-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Workers 环境配置
[env.production]
name = "recipe-api"

[env.staging]
name = "recipe-api-staging"

# 路由配置 (可选，如果你有自定义域名)
# routes = [
#   "recipe-api.example.com/*",
#   "api.example.com/recipes/*"
# ]

# 变量配置 (如果需要)
[vars]
ENVIRONMENT = "production"

# KV 存储配置 (如果将来需要持久化存储)
# [[kv_namespaces]]
# binding = "RECIPES_KV"
# id = "your-kv-namespace-id"

# 触发器配置
[triggers]
crons = []